# Generated by Django 5.0.1 on 2024-01-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apitodo', '0003_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
